require: rubocop-rake

AllCops:
  NewCops: enable

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
